import json
import re
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple, Type
from pydantic import BaseModel, ValidationError

from ai.app.schemas.requests import AIExecutionResponse
from ai.app.safety.pii_sanitizer import secret_detector


class FinancialValueValidator:
    """
    Validates that numerical financial figures in AI explanations exactly match
    authoritative ground-truth metrics generated by backend FinancialEngine.
    Prevents hallucinated financial values from silently entering financial workflows.
    """

    def validate_numbers(
        self, explanation_text: str, ground_truth_metrics: Dict[str, Any]
    ) -> Tuple[bool, List[str]]:
        """
        Extracts currency amounts from output text and verifies they match calculated metrics.
        Returns:
            Tuple[is_valid, list_of_hallucination_errors]
        """
        errors = []
        # Extract currency figures from output text e.g. ₹16,726.81 or ₹5,00,000.00
        found_amounts = re.findall(r'₹\s*([\d,]+(?:\.\d+)?)', explanation_text)

        if not ground_truth_metrics or not found_amounts:
            return True, []

        # Convert ground truth values to flat set of strings
        def extract_ground_truth_strings(obj: Any) -> List[str]:
            vals = []
            if isinstance(obj, Decimal):
                vals.append(f"{obj:.2f}")
                vals.append(f"{obj:.0f}")
            elif isinstance(obj, (int, float)):
                vals.append(f"{obj:.2f}")
                vals.append(f"{obj:.0f}")
            elif isinstance(obj, dict):
                for v in obj.values():
                    vals.extend(extract_ground_truth_strings(v))
            elif isinstance(obj, list):
                for item in obj:
                    vals.extend(extract_ground_truth_strings(item))
            return vals

        gt_strings = set(extract_ground_truth_strings(ground_truth_metrics))

        for raw_num in found_amounts:
            num_clean = raw_num.replace(",", "")
            try:
                val = float(num_clean)
                val_str_2f = f"{val:.2f}"
                val_str_0f = f"{val:.0f}"

                # Verify if this number exists in ground truth metrics
                if val_str_2f not in gt_strings and val_str_0f not in gt_strings:
                    # Ignore minor round numbers like ₹100 or ₹12
                    if val > 500:
                        errors.append(f"Mismatched financial value ₹{raw_num}: figure does not match backend FinancialEngine ground truth.")
            except ValueError:
                pass

        return len(errors) == 0, errors


class SchemaValidationGuard:
    """
    Validates model output payload against Pydantic schemas.
    Rejects malformed JSON syntax or invalid schema outputs.
    """

    def validate_schema(self, raw_output: str, schema_cls: Type[BaseModel]) -> Tuple[bool, Optional[BaseModel], str]:
        """
        Validates JSON string against schema.
        """
        try:
            parsed_json = json.loads(raw_output)
            instance = schema_cls(**parsed_json)
            return True, instance, ""
        except json.JSONDecodeError as e:
            return False, None, f"Malformed model output: Invalid JSON syntax ({str(e)})"
        except ValidationError as e:
            return False, None, f"Schema validation failed: {str(e)}"
        except Exception as e:
            return False, None, f"Schema verification error: {str(e)}"


class OutputSanitizer:
    """
    Sanitizes AI outputs to prevent data exfiltration via hidden URLs, markdown images, or webhook callbacks.
    """

    EXFILTRATION_PATTERNS = [
        re.compile(r'!\[.*?\]\((https?://.*?)\)', re.IGNORECASE),  # Markdown exfiltration image
        re.compile(r'<img\s+src=["\'](https?://.*?)["\']', re.IGNORECASE),  # HTML image tag exfiltration
        re.compile(r'https?://[^\s]+\.(?:php|bin|sh|exe)\?[^\s]+', re.IGNORECASE),  # Webhook callbacks with query params
    ]

    def sanitize(self, output_text: str) -> Tuple[str, bool, List[str]]:
        """
        Sanitizes text for exfiltration vectors.
        """
        flags = []
        cleaned = output_text

        for pattern in self.EXFILTRATION_PATTERNS:
            matches = pattern.findall(cleaned)
            if matches:
                flags.append(f"Data exfiltration URL pattern detected: {matches[0]}")
                cleaned = pattern.sub("[REDACTED_EXFILTRATION_URL]", cleaned)

        return cleaned, len(flags) > 0, flags


class DecisionGuard:
    """
    Enforces non-authoritative financial boundaries, schema checks, and secret leakage prevention on AI outputs.
    """

    def __init__(self):
        self.financial_validator = FinancialValueValidator()
        self.schema_guard = SchemaValidationGuard()
        self.output_sanitizer = OutputSanitizer()

    def enforce(
        self, response: AIExecutionResponse, role: str, ground_truth_metrics: Optional[Dict[str, Any]] = None
    ) -> AIExecutionResponse:
        """
        Enforces safety boundaries on AI outputs.
        """
        # 1. Underwriting / risk recommendations MUST require human banker review
        if response.recommendation in ["approve", "reject"]:
            response.requires_human_review = True

        # 2. Ensure recommendation is constrained to allowed enum values
        if response.recommendation not in ["approve", "review", "reject", "escalate"]:
            response.recommendation = "review"

        # 3. Secret Leakage Check on output
        cleaned_resp, secrets_found, secret_labels = secret_detector.detect_and_redact(response.response)
        if secrets_found:
            response.response = cleaned_resp
            response.requires_human_review = True
            response.recommendation = "review"
            response.evidence.append(f"[Safety Guard] Redacted secret leakage in output: {secret_labels}")

        # 4. Data Exfiltration Check
        sanitized_resp, exfil_found, exfil_flags = self.output_sanitizer.sanitize(response.response)
        if exfil_found:
            response.response = sanitized_resp
            response.requires_human_review = True
            response.recommendation = "escalate"
            response.evidence.append(f"[Safety Guard] Data exfiltration attempt blocked: {exfil_flags}")

        # 5. Financial Value Validation (if ground truth metrics provided)
        if ground_truth_metrics:
            is_valid_math, math_errors = self.financial_validator.validate_numbers(response.response, ground_truth_metrics)
            if not is_valid_math:
                response.requires_human_review = True
                response.recommendation = "review"
                response.evidence.append(f"[Safety Guard] Mismatched financial numbers detected: {math_errors}")

        # Explicitly append non-authoritative disclaimer to reasoning
        disclaimer = " [Non-authoritative AI prediction. Final decision requires authoritative policy validation/banker review.]"
        if not response.reasoning_summary.endswith(disclaimer):
            response.reasoning_summary += disclaimer

        return response


decision_guard = DecisionGuard()
financial_value_validator = FinancialValueValidator()
schema_validation_guard = SchemaValidationGuard()
output_sanitizer = OutputSanitizer()
