import json
import urllib.request
import urllib.error
from typing import Dict, Any, Tuple
from ai.app.providers.base import BaseProvider
from ai.app.core.config import ai_settings
from ai.app.core.exceptions import ProviderAPIError
from ai.app.schemas.requests import AIExecutionRequest


class GeminiProvider(BaseProvider):
    """Google Gemini LLM Provider Adapter."""

    def __init__(self, api_key: str | None = None):
        key = api_key or ai_settings.gemini_api_key or ai_settings.ai_api_key
        super().__init__(provider_name="gemini", api_key=key)

    def is_available(self) -> bool:
        return bool(self.api_key and len(self.api_key.strip()) > 0)

    async def generate(
        self,
        request: AIExecutionRequest,
        prompt_text: str,
        model_id: str = "gemini-1.5-flash",
    ) -> Tuple[str, Dict[str, Any]]:
        if not self.is_available():
            raise ProviderAPIError("gemini", "Gemini API key is not configured.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_id}:generateContent?key={self.api_key}"
        payload = {
            "contents": [{
                "parts": [{"text": prompt_text}]
            }],
            "generationConfig": {
                "temperature": request.temperature,
                "maxOutputTokens": request.max_tokens,
            }
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )

        try:
            with urllib.request.urlopen(req, timeout=ai_settings.timeout_seconds) as response:
                res_body = json.loads(response.read().decode("utf-8"))
                candidates = res_body.get("candidates", [])
                if not candidates:
                    raise ProviderAPIError("gemini", "No candidate text generated by Gemini.")
                
                text_content = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                usage_metadata = res_body.get("usageMetadata", {})

                meta = {
                    "prompt_tokens": usage_metadata.get("promptTokenCount", len(prompt_text.split())),
                    "completion_tokens": usage_metadata.get("candidatesTokenCount", len(text_content.split())),
                    "finish_reason": candidates[0].get("finishReason", "STOP"),
                    "provider": "gemini",
                    "model_id": model_id,
                }
                return text_content, meta
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8") if e.fp else str(e)
            raise ProviderAPIError("gemini", f"HTTP {e.code}: {err_msg}", status_code=e.code)
        except Exception as e:
            raise ProviderAPIError("gemini", str(e), status_code=500)
