"""make loan application_id unique

Revision ID: bcfaca1904c3
Revises: fdeec8ce6ca7
Create Date: 2026-08-20 02:07:20.782478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcfaca1904c3'
down_revision: Union[str, Sequence[str], None] = 'fdeec8ce6ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_application_id'), table_name='loans')
    op.create_index(op.f('ix_loans_application_id'), 'loans', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_application_id'), table_name='loans')
    op.create_index(op.f('ix_loans_application_id'), 'loans', ['application_id'], unique=False)
    # ### end Alembic commands ###
